### ISSUE TITLE
Can't install directly from github.

### ISSUE THREAD

**Issue by abuiles** [the-refinery/ember-devise-simple-auth#15]
It depends on 'dist/bower.json' but it's not found.

``` bash
There was a Errno::ENOENT while loading ember_devise_simple_auth.gemspec: 
No such file or directory - /Users/adolfo/.rvm/gems/ruby-2.0.0-p0@facturas/bundler/gems/ember-devise-simple-auth-7f420775a30e/dist/bower.json from
  /Users/adolfo/.rvm/gems/ruby-2.0.0-p0@facturas/bundler/gems/ember-devise-simple-auth-7f420775a30e/ember_devise_simple_auth.gemspec:4:in `<main>'
```

**Comment by mbixby** [comment]
+1

**Comment by joefiorini** [comment]
This is still an issue, unfortunately. I'm sharing the version with the bower component, which I have symlinked to a dist directory. If you do that too, it should work. I think we're going to need to separate the gem from the plugin at some point in the near future. I've put a band-aid in place to fix the generator issues for now, but I'll leave this open until I split out the gem.

**Comment by jayeff** [comment]
Here are all the steps I went through to get the example app running on my machine:
- Clone d-i/ember-devise-simple-auth
- Clone d-i/ember-devise-simple-auth-bower
- cd into ember-devise-simple-auth
- run `npm install`
- run build script `./build.sh`
- check if `dist` is correctly symlinked [1]

```
> ls -l dist
lrwxr-xr-x  1 xxxx  staff  33 23 Mär 13:43 dist -> ../ember-devise-simple-auth-bower
```
- cd into /examples/ember-rails
- Remove the currently symlinked ember-devise-simple-auth: `rm vendor/assets/bower_components/ember-devise-simple-auth`
- Symlink to your cloned `ember-devise-simple-auth-bower` repository: `ln -s <path/to>/ember-devise-simple-auth-bower/ vendor/assets/bower_components/ember-devise-simple-auth`
- run `bundle install` (Currently sprockets is locked to the yanked version 2.11.1, run `bundle update sprockets` to get a working version - this should be fixed by my PR #24)
- run `rake db:migrate`, run `rake db:seed`
- fire up the rails server `bin/rails s`

This was a little bit more complicated than described in `examples/ember-rails/README.md` - Running the example.
Should the description be updated?

[1] Note: If you run the build-script without the cloned `ember-devise-simple-auth-bower` the project will be build, but `dist/bower.json` is missing and you will get the same error as described above by @abuiles. You will also need broccoli-cli (required by build.sh for the "real" build: `npm install --global broccoli-cli`)

Update:
added the symlink steps within examples/rails-ember

**Comment by danbartlett** [comment]
I've been struggling to get ember-devise-simple-auth working properly with ember-rails, and so I tried setting up the example, and eventually (after much frustration) found this issue. Maybe update the description as @jayeff suggests.

Following these steps `./build.sh` fails, complaining about 'broccoli-es6-module-filter' and 'broccoli-concat' - I didn't realise they were dependencies at first, but them just `npm install` ed them too. Finally I get stuck on:

```
./build.sh: 1: ./build.sh: [[: not found

/home/dan/ember-devise-simple-auth/node_modules/broccoli/lib/builder.js:150
    throw new Error('Exporting a function in Brocfile.js is no longer supporte
          ^
Error: Exporting a function in Brocfile.js is no longer supported. Export a tree instead. To update, turn this

    module.exports = function (broccoli) {
      ...
      return someTree;
    };

into this

    ...
    module.exports = someTree;

    at Object.loadBrocfile (/home/dan/ember-devise-simple-auth/node_modules/broccoli/lib/builder.js:150:11)
    at getBuilder (/home/dan/ember-devise-simple-auth/node_modules/broccoli/lib/cli.js:71:23)
    at Command.<anonymous> (/home/dan/ember-devise-simple-auth/node_modules/broccoli/lib/cli.js:30:21)
    at Command.<anonymous> (/home/dan/ember-devise-simple-auth/node_modules/broccoli/node_modules/commander/index.js:249:8)
    at Command.EventEmitter.emit (events.js:98:17)
    at Command.parseArgs (/home/dan/ember-devise-simple-auth/node_modules/broccoli/node_modules/commander/index.js:478:12)
    at Command.parse (/home/dan/ember-devise-simple-auth/node_modules/broccoli/node_modules/commander/index.js:370:21)
    at Object.broccoliCLI [as cli] (/home/dan/ember-devise-simple-auth/node_modules/broccoli/lib/cli.js:63:11)
    at Object.<anonymous> (/usr/lib/node_modules/broccoli-cli/bin/broccoli:11:10)
    at Module._compile (module.js:456:26)
```

I've tried tweaking the Brocfile.js but with no luck. Any ideas?
